source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

pod "VMLogger", :path => '../../VMLogger'

target 'VMLogger_Example' do
  
end

target 'VMLogger_Tests' do
  pod "VMLogger", :path => '../../VMLogger'

end
